# Generated by Django 4.2 on 2023-12-14 13:07

from django.db import migrations, models
import enumfields.fields
import payment.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    enumfields.fields.EnumField(
                        default=("P", "Pending"),
                        enum=payment.models.Payment.StatusChoices,
                        max_length=16,
                    ),
                ),
                (
                    "type",
                    enumfields.fields.EnumField(
                        default=("P", "Payment"),
                        enum=payment.models.Payment.TypeChoices,
                        max_length=16,
                    ),
                ),
                ("borrowing_id", models.IntegerField()),
                ("session_url", models.CharField(max_length=255)),
                ("session_id", models.CharField(max_length=255)),
                (
                    "money_to_pay",
                    models.DecimalField(decimal_places=2, max_digits=10000),
                ),
            ],
        ),
    ]
