# Generated by Django 5.0 on 2023-12-14 11:07

import book.models
import enumfields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_alter_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=enumfields.fields.EnumField(
                default=("H", "Hardcover"),
                enum=book.models.Book.CoverChoices,
                max_length=18,
            ),
        ),
    ]
