# Generated by Django 5.0 on 2023-12-14 11:47

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_alter_book_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(
                null=True, upload_to=book.models.book_image_file_path
            ),
        ),
    ]
